### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by yupferris** [kristianhasselknippe/fuse-mode#11]
I'm currently looking at #3 (uno syntax highlighting), and I think the best way to implement it is to fork csharp-mode.el and start patching it for uno's needs. This means, for both copyright and attribution, that the patched code must be released under a gpl-compatible license. We can use such a license for that file only if we want, but we should also take the opportunity to choose a license for the project at large. For simplicity I recommend gpl-v2 as csharp-mode uses this (and we'll likely run into something similar if we fork nxml-mode; I was unable to find any specific license information for that project after a quick check but it seems to be a gnu project which means it's gpl as well), although typically I tend to prefer 2-clause BSD or MIT (neither of which are gpl-compatible).

@cbaggers should give his 2 cents about the issue, as he's probably the most knowledgable about these things.

**Comment by kristianhasselknippe** [comment]
@yupferris  Had a chat with Chris and he thinks there is no reason for use not to choose gpl-v2 :), so im gonna go with that :D
